### ISSUE TITLE
Error when running obj2mjcf 

### ISSUE THREAD

**Issue by rs545837** [kevinzakka/obj2mjcf#24]
The following error pops up when I run  
``` bash
obj2mjcf --obj-dir . --save-mjcf --compile-model --verbose
```
in the directory containing my .obj files, although after running, it's generating a folder containing my processed obj file.
``` 
Traceback (most recent call last):
  File "/opt/homebrew/bin/obj2mjcf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/obj2mjcf/_cli.py", line 560, in main
    process_obj(obj_file, args)
  File "/opt/homebrew/lib/python3.11/site-packages/obj2mjcf/_cli.py", line 473, in process_obj
    obj_body, "geom", material=material.name, mesh=str(meshname.stem)
                               ^^^^^^^^
UnboundLocalError: cannot access local variable 'material' where it is not associated with a value
```

**Comment by rs545837** [comment]
Oh thanks for it, although I ended up using some other way to reach the goal I was trying to achieve.
